-- Migration: Create Tracked Accounts Table
-- Description: Stores "favorited" player tags for logged-in users

CREATE TABLE IF NOT EXISTS public.tracked_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    player_tag TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, player_tag)
);

-- Enable RLS
ALTER TABLE public.tracked_accounts ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can view their own tracked accounts" ON public.tracked_accounts FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own tracked accounts" ON public.tracked_accounts FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own tracked accounts" ON public.tracked_accounts FOR DELETE USING (auth.uid() = user_id);
